### ISSUE TITLE
Implement Support for LaTeX Builder

### ISSUE THREAD

**Issue by tobydriscoll** [executablebooks/sphinx-proof#55]
**Describe the bug**

Any `prf:xxx` directive (including `prf:proof`) causes the latex builder to error out, even when the html builder is fine.

**To Reproduce**

content file:
````
# Testing
Here is a theorem.

```{prf:theorem} Important theorem
It's true.
```
````
_config.yml:
```
# Book settings
title: FUBAR
author: Me

latex:
  latex_documents:
    targetname: mybook.tex

sphinx:
  extra_extensions:
    - sphinx_proof
```
TOC file has just the content MD file.

````
jb build . --builder latex                                                                                                               
Running Jupyter-Book v0.10.1
Source Folder: /home/driscoll/Documents/tmp-latexbook
Config Path: /home/driscoll/Documents/tmp-latexbook/_config.yml
Output Path: /home/driscoll/Documents/tmp-latexbook/_build/latex
Running Sphinx v3.5.1
myst v0.13.3: MdParserConfig(renderer='sphinx', commonmark_only=False, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, update_mathjax=True, enable_extensions=['colon_fence', 'dollarmath', 'linkify', 'substitution'], disable_syntax=[], url_schemes=['mailto', 'http', 'https'], heading_anchors=None, html_meta=[], footnote_transition=True, substitutions=[], sub_delimiters=['{', '}'])
building [mo]: targets for 0 po files that are out of date
building [latex]: all documents
updating environment: [new config] 1 added, 0 changed, 0 removed
reading sources... [100%] overview                                                                                                                                                                  
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
processing python.tex... overview 
resolving references...
done
writing... failed

Exception occurred:
  File "/home/driscoll/anaconda3/lib/python3.7/site-packages/sphinx/writers/latex.py", line 2072, in unknown_visit
    raise NotImplementedError('Unknown node: ' + node.__class__.__name__)
NotImplementedError: Unknown node: enumerable_node
The full traceback has been saved in /tmp/sphinx-err-aledue__.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Traceback (most recent call last):
  File "/home/driscoll/anaconda3/lib/python3.7/site-packages/jupyter_book/sphinx.py", line 150, in build_sphinx
    app.build(force_all, filenames)
  File "/home/driscoll/anaconda3/lib/python3.7/site-packages/sphinx/application.py", line 352, in build
    self.builder.build_update()
  File "/home/driscoll/anaconda3/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 293, in build_update
    self.build(['__all__'], to_build)
  File "/home/driscoll/anaconda3/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 360, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/driscoll/anaconda3/lib/python3.7/site-packages/sphinx/builders/latex/__init__.py", line 304, in write
    docwriter.write(doctree, destination)
  File "/home/driscoll/anaconda3/lib/python3.7/site-packages/docutils/writers/__init__.py", line 78, in write
    self.translate()
  File "/home/driscoll/anaconda3/lib/python3.7/site-packages/sphinx/writers/latex.py", line 101, in translate
    self.document.walkabout(visitor)
  File "/home/driscoll/anaconda3/lib/python3.7/site-packages/docutils/nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  File "/home/driscoll/anaconda3/lib/python3.7/site-packages/docutils/nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  File "/home/driscoll/anaconda3/lib/python3.7/site-packages/docutils/nodes.py", line 206, in walkabout
    visitor.dispatch_visit(self)
  File "/home/driscoll/anaconda3/lib/python3.7/site-packages/sphinx/util/docutils.py", line 471, in dispatch_visit
    super().dispatch_visit(node)
  File "/home/driscoll/anaconda3/lib/python3.7/site-packages/docutils/nodes.py", line 1995, in dispatch_visit
    return method(node)
  File "/home/driscoll/anaconda3/lib/python3.7/site-packages/sphinx/writers/latex.py", line 2072, in unknown_visit
    raise NotImplementedError('Unknown node: ' + node.__class__.__name__)
NotImplementedError: Unknown node: enumerable_node

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/driscoll/anaconda3/bin/jb", line 8, in <module>
    sys.exit(main())
  File "/home/driscoll/anaconda3/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/driscoll/anaconda3/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/driscoll/anaconda3/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/driscoll/anaconda3/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/driscoll/anaconda3/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/driscoll/anaconda3/lib/python3.7/site-packages/jupyter_book/commands/__init__.py", line 305, in build
    result, builder, OUTPUT_PATH, build_type, PAGE_NAME, click.echo
  File "/home/driscoll/anaconda3/lib/python3.7/site-packages/jupyter_book/commands/__init__.py", line 546, in builder_specific_actions
    raise RuntimeError(_message_box(msg, color="red", doprint=False)) from result
RuntimeError: 
===============================================================================

There was an error in building your book. Look above for the cause.

===============================================================================
````

**Expected behavior**

Successful production of tex file.
**Environment**
- Python Version [e.g. 3.7.1]: 3.7.6
- Sphinx version: 3.5.1
- Package versions or output of `jupyter-book --version`:
Jupyter Book: 0.10.1
MyST-NB: 0.12.0
Sphinx Book Theme: 0.0.39
MyST-Parser: 0.13.3
Jupyter-Cache: 0.4.2
NbClient: 0.5.3

- Operating System:
Linux, Mac OS (for M1)

**Additional context**

Contents of sphinx log file below. I can't understand why sphinx_proof does not appear in the list of loaded extensions, but again, it all works fine with the default html builder.

```
# Sphinx version: 3.5.1
# Python version: 3.7.6 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 2.11.3
# Last messages:
#   0 added, 0 changed, 0 removed
#   looking for now-outdated files...
#   none found
#   processing python.tex...
#   overview
#   
#   resolving references...
#   done
#   writing...
#   failed
# Loaded extensions:
#   sphinx.ext.mathjax (3.5.1) from /home/driscoll/anaconda3/lib/python3.7/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /home/driscoll/anaconda3/lib/python3.7/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /home/driscoll/anaconda3/lib/python3.7/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (1.0.3) from /home/driscoll/anaconda3/lib/python3.7/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.4) from /home/driscoll/anaconda3/lib/python3.7/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /home/driscoll/anaconda3/lib/python3.7/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /home/driscoll/anaconda3/lib/python3.7/site-packages/alabaster/__init__.py
#   sphinx_togglebutton (0.2.3) from /home/driscoll/anaconda3/lib/python3.7/site-packages/sphinx_togglebutton/__init__.py
#   sphinx_copybutton (0.3.1) from /home/driscoll/anaconda3/lib/python3.7/site-packages/sphinx_copybutton/__init__.py
#   myst_nb (0.12.0) from /home/driscoll/anaconda3/lib/python3.7/site-packages/myst_nb/__init__.py
#   jupyter_book (0.10.1) from /home/driscoll/anaconda3/lib/python3.7/site-packages/jupyter_book/__init__.py
#   sphinx_thebe (0.0.8) from /home/driscoll/anaconda3/lib/python3.7/site-packages/sphinx_thebe/__init__.py
#   sphinx_comments (0.0.3) from /home/driscoll/anaconda3/lib/python3.7/site-packages/sphinx_comments/__init__.py
#   sphinx.ext.intersphinx (3.5.1) from /home/driscoll/anaconda3/lib/python3.7/site-packages/sphinx/ext/intersphinx.py
#   sphinx_panels (0.5.2) from /home/driscoll/anaconda3/lib/python3.7/site-packages/sphinx_panels/__init__.py
#   sphinx_book_theme (unknown version) from /home/driscoll/anaconda3/lib/python3.7/site-packages/sphinx_book_theme/__init__.py
Traceback (most recent call last):
  File "/home/driscoll/anaconda3/lib/python3.7/site-packages/jupyter_book/sphinx.py", line 150, in build_sphinx
    app.build(force_all, filenames)
  File "/home/driscoll/anaconda3/lib/python3.7/site-packages/sphinx/application.py", line 352, in build
    self.builder.build_update()
  File "/home/driscoll/anaconda3/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 293, in build_update
    self.build(['__all__'], to_build)
  File "/home/driscoll/anaconda3/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 360, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/driscoll/anaconda3/lib/python3.7/site-packages/sphinx/builders/latex/__init__.py", line 304, in write
    docwriter.write(doctree, destination)
  File "/home/driscoll/anaconda3/lib/python3.7/site-packages/docutils/writers/__init__.py", line 78, in write
    self.translate()
  File "/home/driscoll/anaconda3/lib/python3.7/site-packages/sphinx/writers/latex.py", line 101, in translate
    self.document.walkabout(visitor)
  File "/home/driscoll/anaconda3/lib/python3.7/site-packages/docutils/nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  File "/home/driscoll/anaconda3/lib/python3.7/site-packages/docutils/nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  File "/home/driscoll/anaconda3/lib/python3.7/site-packages/docutils/nodes.py", line 206, in walkabout
    visitor.dispatch_visit(self)
  File "/home/driscoll/anaconda3/lib/python3.7/site-packages/sphinx/util/docutils.py", line 471, in dispatch_visit
    super().dispatch_visit(node)
  File "/home/driscoll/anaconda3/lib/python3.7/site-packages/docutils/nodes.py", line 1995, in dispatch_visit
    return method(node)
  File "/home/driscoll/anaconda3/lib/python3.7/site-packages/sphinx/writers/latex.py", line 2072, in unknown_visit
    raise NotImplementedError('Unknown node: ' + node.__class__.__name__)
NotImplementedError: Unknown node: enumerable_node
```

**Comment by AakashGfude** [comment]
Thanks, @tobydriscoll for the issue. Looks like some nodes in this repo have not been implemented for the latex build. We will work on it soon :)

**Comment by mmcky** [comment]
@AakashGfude here are some `LaTeX` resources for `proof` and `theorems`

https://www.overleaf.com/learn/latex/Theorems_and_proofs

**Comment by AakashGfude** [comment]
@tobydriscoll this issue has been resolved with this PR https://github.com/executablebooks/sphinx-proof/pull/58 , `v0.1.0` onwards will have the fix.
