### ISSUE TITLE
Jupyter Book requires title for theorems

### ISSUE THREAD

**Issue by kmoy1** [executablebooks/sphinx-proof#57]
Using WSL Ubuntu 20.04 and Jupyter Books, all directives except proofs seem to require a title. 

For example, when writing a simple test theorem via
```

````{prf:theorem}
Dummy Theorem
\````
````

in a Markdown file, at build time this results in

```
writing output... [ 50%] Ch2/intro
Exception occurred:
  File "/home/kevinmoy/.local/lib/python3.8/site-packages/sphinx_proof/nodes.py", line 36, in depart_enumerable_node
    idx = self.body.index(f"Proof {number} ")
ValueError: 'Proof  ' is not in list
Traceback (most recent call last):
  File "/home/kevinmoy/.local/lib/python3.8/site-packages/jupyter_book/sphinx.py", line 150, in build_sphinx
    app.build(force_all, filenames)
  File "/home/kevinmoy/.local/lib/python3.8/site-packages/sphinx/application.py", line 352, in build
    self.builder.build_update()
  File "/home/kevinmoy/.local/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 296, in build_update
    self.build(to_build,
  File "/home/kevinmoy/.local/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 360, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/kevinmoy/.local/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 534, in write
    self._write_serial(sorted(docnames))
  File "/home/kevinmoy/.local/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 544, in _write_serial
    self.write_doc(docname, doctree)
  File "/home/kevinmoy/.local/lib/python3.8/site-packages/sphinx/builders/html/__init__.py", line 605, in write_doc
    self.docwriter.write(doctree, destination)
  File "/home/kevinmoy/.local/lib/python3.8/site-packages/docutils/writers/__init__.py", line 78, in write
    self.translate()
  File "/home/kevinmoy/.local/lib/python3.8/site-packages/sphinx/writers/html.py", line 71, in translate
    self.document.walkabout(visitor)
  File "/home/kevinmoy/.local/lib/python3.8/site-packages/docutils/nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  File "/home/kevinmoy/.local/lib/python3.8/site-packages/docutils/nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  File "/home/kevinmoy/.local/lib/python3.8/site-packages/docutils/nodes.py", line 227, in walkabout
    visitor.dispatch_departure(self)
  File "/home/kevinmoy/.local/lib/python3.8/site-packages/sphinx/util/docutils.py", line 485, in dispatch_departure
    method(node)
  File "/home/kevinmoy/.local/lib/python3.8/site-packages/sphinx_proof/nodes.py", line 36, in depart_enumerable_node
    idx = self.body.index(f"Proof {number} ")
ValueError: 'Proof  ' is not in list
....
```

But this is fixed when I add a title to the theorem/directive:

```

````{prf:theorem} Theorem
Dummy Theorem
\````
```

The same goes for corollaries, proofs, observations, etc. Basically everything except proofs needs a title, and having to come up with titles for each is somewhat annoying. Is there a way to work around this?

**Comment by AakashGfude** [comment]
Hello @kmoy1 , the issue has been fixed now in `v0.1.0`.
